### ISSUE TITLE
alas在linux服务器上管理困难

### ISSUE THREAD

**Issue by amountnothing** [linwei5d/Alas#1]
## 树莓派4b运行
**设备环境**
树莓派4b
系统: omv6
**问题/需求**
没有端口可以允许从外部管理，无法直接从电脑访问alas，也不知道alas内部什么情况

**运行日志**
════════════════════════════════════════════════════════════════════════════════
                                     START                                      
════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════════════════════════════════════════════
                                     START                                      
════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════════════════════════════════════════════
                                     START                                      
════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════════════════════════════════════════════
.......
后面全部一样

**Comment by linwei5d** [comment]
经过初步DEBUG得知，当docker挂载设备上的文件的时候，会因为奇怪的权限问题无法加载配置文件导致Alas启动失败。
解决方法：把Alas文件挂载到/app/temp，然后在容器内执行rm-rf /app/Alas && cp /app/temp /app/Alas -r，重启容器即可

**Comment by linwei5d** [comment]
新的docker镜像会在1周之内更新，同时也会更新github教程，最好的方法是只挂载config文件夹内的内容，因为本人不定时退坑，很可能导致镜像没有更新，最好手动更新

**Comment by amountnothing** [comment]
谢谢
